import React from "react";
import "./ItineraryPage.css";
import { Link } from "react-router-dom";
import logo from '../assets/logo2.png';

const ItineraryPage = () => {
  return (
  
    <div className="itinerary-page">
       <header className="navbar">
        <div className="logo">
          <img src={logo} alt="Travel AI Logo" />
          <h1>Travel AI</h1>
        </div>
        <nav>
          <ul>
            {/* <li><a href="#features">Features</a></li> */}
            <li><Link to="/">Home</Link></li>
            <li><Link to="/login">Login</Link></li>
            

          </ul>
        </nav>
      </header>
      {/* Sidebar */}
      <aside className="sidebar">
        <nav>
          <ul>
            <li>
              <a href="#itinerary">Itinerary</a>
            </li>
            <li>
              <a href="#weather">Weather</a>
            </li>
            <li>
              <a href="#flights">Flights</a>
            </li>
            <li>
              <a href="#buses">Buses</a>
            </li>
            <li>
              <a href="#hotels">Hotels</a>
            </li>
            <li>
              <a href="#cab-services">Cab Services</a>
            </li>
            <li>
              <a href="#local-restaurants">Local Restaurants</a>
            </li>
          </ul>
        </nav>
      </aside>

      {/* Main Content */}
      <main className="main-content">
        <section id="itinerary">
          <h2>Itinerary</h2>
          <p>
            Here's your travel itinerary generated by Gemini:
          </p>
          <div className="itinerary-details">
            <ul>
              <li>
                <strong>Day 1:</strong> Arrival in Paris, Eiffel Tower visit.
              </li>
              <li>
                <strong>Day 2:</strong> Louvre Museum and Seine River cruise.
              </li>
              <li>
                <strong>Day 3:</strong> Versailles Palace tour.
              </li>
              <li>
                <strong>Day 4:</strong> Departure.
              </li>
            </ul>
          </div>
        </section>

        <section id="weather">
          <h2>Weather</h2>
          <p>Check the latest weather conditions at your destination.</p>
        </section>

        <section id="flights">
          <h2>Flights</h2>
          <p>Find the best flight options for your trip.</p>
        </section>

        <section id="buses">
          <h2>Buses</h2>
          <p>Explore bus services and routes for your travel.</p>
        </section>

        <section id="hotels">
          <h2>Hotels</h2>
          <p>Book accommodations for your stay.</p>
        </section>

        <section id="cab-services">
          <h2>Cab Services</h2>
          <p>Find reliable cab services at your destination.</p>
        </section>

        <section id="local-restaurants">
          <h2>Local Restaurants</h2>
          <p>Discover the best local restaurants and cuisine.</p>
        </section>
      </main>
    </div>
  );
};

export default ItineraryPage;
